# Site
name: Choosebyte
description:
meta_description: "Santosh Kumar's Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 15
baseurl: /
google_analytics: 'UA-120724518-1'
disqus: 'choosebyte'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  sal:
    name: Santosh Kumar
    display_name: Santosh Kumar
    gravatar: 490533114d37d4e77f19a6df14e43d7b
    email: developer.santoshk@gmail.com
    web: https://santoshkumar.io
    twitter: https://twitter.com/santoshkumar_io
    description: "Full Stack Software Engineer in PHP and NodeJS."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge